version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'shopware'
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
      MYSQL_DATABASE: shopware
    volumes:
      - mysql-data:/var/lib/mysql

  init-perm:
    image: alpine
    volumes:
      - files:/var/www/html/files
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - sitemap:/var/www/html/public/sitemap
    command: chown 82:82 /var/www/html/files /var/www/html/public/theme /var/www/html/public/media /var/www/html/public/thumbnail /var/www/html/public/sitemap

  init:
    image: local
    build:
      context: .
    env_file: .app.env
    entrypoint: /setup
    volumes:
      - files:/var/www/html/files
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - sitemap:/var/www/html/public/sitemap
    depends_on:
      db:
        condition: service_started
      init-perm:
        condition: service_completed_successfully
  web:
    image: local
    build:
      context: .
    volumes:
      - files:/var/www/html/files
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - sitemap:/var/www/html/public/sitemap
    depends_on:
      init:
        condition: service_completed_successfully
    env_file: .app.env
    ports:
      - 8000:8000

  worker:
    image: local
    restart: unless-stopped
    build:
      context: .
    volumes:
      - files:/var/www/html/files
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - sitemap:/var/www/html/public/sitemap
    depends_on:
      init:
        condition: service_completed_successfully
    env_file: .app.env
    entrypoint: [ "php", "bin/console", "messenger:consume", "async", "low_priority", "--time-limit=300", "--memory-limit=512M" ]
    deploy:
      replicas: 3

  scheduler:
    image: local
    restart: unless-stopped
    build:
      context: .
    volumes:
      - files:/var/www/html/files
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - sitemap:/var/www/html/public/sitemap
    depends_on:
      init:
        condition: service_completed_successfully
    env_file: .app.env
    entrypoint: [ "php", "bin/console", "scheduled-task:run" ]

volumes:
  mysql-data:
  files:
  theme:
  media:
  thumbnail:
  sitemap: